#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
import os
if sys.version_info < (3, 6, 0):
   sys.exit(f'[ERROR]: {__file__} Can\'t Run, Please Upgrade Python Installed On System!')

if not ('posix' in sys.builtin_module_names):
   sys.exit(f'[ERROR]: {__file__} Can\'t Run, Please Run On POSIX OS System!')


import pwd
import socket
import subprocess
from  pathlib import Path
from  argparse import ArgumentParser, ArgumentTypeError

root_path = Path(sys.argv[0]).resolve().parent

################################################################
__author__ = 'Viocal Pan <viocal@qq.com>'
__run__ = 'pyscp.py'  #os.path.splitext(__file__)[0]
__app__ = Path(__run__).stem
__path__ = str(root_path)
__run__  = Path(sys.argv[0]).stem

appName = __app__
appVer = '0.6.0'
appPath = __path__
appDesc = '  -- scp to multiple hosts at once from greenplum\'s gpscp'

gargv = {'allHosts': [], 'hostname':None, 'curUser':None, 'char':'=', 'dir':False}

################################################################
def is_file(path):
    if not Path(path).is_file():
        raise ArgumentTypeError('[ERROR]: Provided file is not a file: {}'.format(path))
    return  str(Path(path).resolve())

################
cmdarg = None
def  parseargs():
    global cmdarg
    parser = ArgumentParser(prog=appName, description=''.join((appName,appDesc)))
    parser.add_argument('-ver', action='version',
             version = f'{appName}{appDesc} version:[{appVer}]')
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument('-a', '--add', dest='addhost', nargs='+',
             help = 'the new host to connect to(multiple -a is okay)')
    group.add_argument('-f', '--file', dest='allhost', type=is_file,
             help = 'a file listing all new hosts to connect to')
    parser.add_argument('-r', dest='dir', action='store_true', default=gargv['dir'],
             help = 'recursively copy entire directories')
    parser.add_argument('filepath', nargs='+',
             help='fle1 file2 ... filen for transport to remote')
    parser.add_argument('-c', dest='char', default=gargv['char'], #type = is_file,
             help = f'character to be substitute as hostname [default {gargv["char"]} ]')
    cmdarg = parser.parse_args()

parseargs()

if __run__ !=  __app__:
   sys.exit(f'[ERROR]: {__run__} Can\'t Run, Please Upgrade Python Installed On System!')

################################################################
def to_str(S):
  if isinstance(S, bytes):
      value = S.decode('utf-8')
  else:
      value = S
  return value

########
def readfline(filename):
   filename = Path(filename)
   LineV = []
   if filename.is_file():
      filename = str(filename.resolve())
      f = None
      try:
         f = open(filename, 'r')
         lines = f.readlines()
         for line in lines:
            line = line.strip()
            if not len(line):
               continue
            L = line.split('#')[0]
            L = L.strip()
            if not len(L):
               continue
            V = L.split()[0]
            V = V.strip()
            if V: LineV.append(V)
      except Exception as Err:
         pass
      finally:
         if f: f.close()
         return LineV

########
def runlocalcmd(cmdstr,cwd='.'):
     p = subprocess.Popen(cmdstr, cwd=cwd, stdout = subprocess.PIPE, stderr = subprocess.PIPE, shell=True)
     out,err = p.communicate()
     retcode = p.returncode
     if not err:
        return  retcode, to_str(out).strip()
     else:
        return  retcode, to_str(err).strip()

########
def  ping(Lsthosts, port=22, timeout=2.0):
   result = []
   for host in Lsthosts:
      try:
          tcp_client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
          tcp_client.settimeout(timeout)
          tcp_client.connect((host,port))
          result.append(host)
      except Exception as Err:
          pass
      finally:
          tcp_client.close()
   return  result

################################################################
if cmdarg.addhost:
    gargv['allHosts'].extend(cmdarg.addhost)
if cmdarg.allhost:
    gargv['allHosts'].extend(readfline(cmdarg.allhost))

gargv['char'] = cmdarg.char[0]
gargv['dir'] = cmdarg.dir

gargv['allHosts'] = list(set(gargv['allHosts']))
gargv['filepath'] = cmdarg.filepath

################################################################
def  collectHosts():
######################
    print(f'\r\n[STEP 1 of 2] create hostlist and local hostname and remote hostname')

# current user & local hostname & ip
    gargv['hostname'] = socket.gethostname()
    gargv['curUser'] = pwd.getpwuid(os.getuid()).pw_name
    LlocalHosts = []
    LlocalIP = []
    LremoteHosts = []

# collect local ip
# ip -o -4 addr show up primary scope global | awk '{print $4}'|cut -f1 -d"/"
# ip addr show |grep -iw inet |grep -iv 127.0.0.1| awk '{print $2}'|cut -f1 -d"/"
# ifconfig |grep -iw inet|grep -iv 127.0.0.1 |awk '{print $2}'|cut -f2 -d":"

    cmdLOCALipGet1 = 'ip -o -4 addr show up primary scope global | awk \'{print $4}\'|cut -f1 -d"/"'
    cmdLOCALipGet2 = 'ifconfig |grep -iw inet|grep -iv 127.0.0.1 |awk \'{print $2}\'|cut -f2 -d":"'
    rc,rs = runlocalcmd(f'{cmdLOCALipGet1} || {cmdLOCALipGet2}')
    if rc != 0:
       exit(f'[ERROR]: {__run__} collect local ip {rs}!')
    LlocalIP = rs.split()
    if len(LlocalIP) == 0:
        exit(f'[ERROR]: {__run__}  can\'t get local ip!')

    LlocalHosts.append(gargv['hostname'])
    for host in gargv['allHosts']:
        try:
            ip = socket.gethostbyname(host)
            if (ip in LlocalIP):
                LlocalHosts.append(host)
                continue
        except Exception as Err:
            continue
        LremoteHosts.append(host)
    LlocalHosts = list(set(LlocalHosts))
    if len(LlocalHosts) > 0:
       LremoteHosts.append(LlocalHosts[0])
    if len(LremoteHosts) == 0:
        exit(f'[ERROR]: {__run__} no host to do !')
    gargv['allHosts'] = ping(LremoteHosts)
    if len(gargv['allHosts']) == 0:
        exit(f'[ERROR]: {__run__} no host to do !')

################################
def  transportFiles():
    print (f'\r\n[STEP 2 of 2] transport on each remote host')

    scp = 'scp -o "BatchMode yes" -o "StrictHostKeyChecking no"'
    if gargv['dir']: scp += ' -r'

    for Rhost in gargv['allHosts']:
        cmd = scp + ' '
        for f in gargv['filepath']:
            cmd += f.replace(gargv['char'], f'  {Rhost}') + '  '
        rc,rs = runlocalcmd(cmd)
        if rc != 0:
           print(f'[ERROR]: {__run__} to {Rhost} {rs}!')
        print (f'***{Rhost}  transport success')

################################################################
try:
    collectHosts()
    transportFiles()

except KeyboardInterrupt:
    sys.exit('\n\nInterrupted...')

finally:
    pass
